[hardware]
; Options: UART_E5, TEST, TEST_UART_E5, TCP
interface_release_av = UART_E5
interface_release_gse = TCP
interface_dev_av = TEST
interface_dev_gse = TEST

; pendant_daemon options: hybrid_device, rpi_gpio_device, f710
; pendant_emulator options: hybrid_device, rpi_gpio_device, f710, emulated_device, hid_device
; pendant_daemon options should always be controlled by a human unless you know exactly what you are doing and have permission from both current GSE and GC lead
controller = hybrid_device

; true means pendant_daemon runs, false means pendant_emulator runs
; pendant_daemon CAN send packets to the server, pendant_emulator can only send packets to the frontend api
send_pendant_state_to_server = false

[tcp]
; only used when [hardware] interface = TCP
; typically 192.168.0.150 for run
gse_ip = 192.168.0.150
; (1-65535) and not overlapping with other ports
; typically 5000 for run, 5001 for dev
gse_port = 5000

path_json_network_device_test=config/network_devices_test.json
path_json_network_device_prod=config/network_devices_prod.json

[lora]
; only used when [hardware] interface = UART_E5
serial_device = /dev/ttyUSB0

; Based off of this AT command
; AT+TEST=RFCFG,928,SF9,500,12,16,22,OFF,OFF,OFF
; AT+TEST=RFCFG,[F],[SF],[BW],[TXPR],[RXPR],[POW],[CRC],[IQ],[NET]
; From https://files.seeedstudio.com/products/317990687/res/LoRa-E5+AT+Command+Specification_V1.0+.pdf#page=53

; in MHz
frequency = 915
spread_factor = SF9
bandwidth = 500
tx_preamble = 12
rx_preamble = 16
; LF and HF max power is 22
power = 22
crc = ON
iq = OFF
net = OFF


[locks]
; Format based on OS if not needed
lock_file_gse_response_path = /tmp/gcs_await_GSE.lock
lock_file_av_response_path = /tmp/gcs_await_AV.lock

[emulation]
; Realistic noise at it's worst is like 0.3
noise_coefficient = 0.0
; Options: 0.0 - 1.0
packet_loss = 0.0
; If true, packet values will emulate arbitrary errors. Otherwise nominal operation
experimental = false

[logging]
; Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
; Invalid options will be silently replaced as INFO
; This is for dev and release mode
level = DEBUG
; Selected Mode For display filter on front end website
level_front = INFO
; When true, use full prefixes: [DEBUG  ] 00006.855 s | name: [STDOUT] message
; When false (e.g. release), use short: [D] 006.85 s | name: message
detailed_logging_prefix = false
cli_log_dir = logs/cli/

[frontend]
; IP address and port for the frontend, default is 0.0.0.0:8008
http_host = 0.0.0.0
http_port = 8008

; IP address and port for the frontend API websocket, default is 127.0.0.1:1887
ws_host = 127.0.0.1
ws_port = 1887

[performance_monitor]
; Performance Monitor Logging Directory
performance_log_dir = logs/performance/

; Performance sampling for logging (seconds)
performance_sampling_interval = 1

; Interval (seconds) that the monitor outputs to the CLI
performance_cli_log_interval = 30
